# Data at UCLH

Data entered into EPIC are stored in data warehouses called Caboodle and Clarity.    

These data can be extracted using SQL by members of Information services teams.    

Extracting data in a format that makes it relatively easy to visualise and analyse may be a complicated process.

[Could we start from something like below to summarise the most commonly requested data and how to use them ?]
 
The data most frequently used are :
 
1. Patient Demographics 
2. Lab components
3. Flowsheets
4. Smartdata elements
5. Diagnoses
6. Medication
7. Encounters
 
[Can we say more about each of the above under headings like this ?]
 
* What are the most commonly requested fields ?
* Patient identifiers (DurableKey vs MRN) and other keys
* Data Codes and where can they be looked up
* Data Labels/Names
* Data Values (are there separate fields for numeric, text values etc.)
* Dates
* Any fields that identify whether values are current
 
How best to extract a particular measurement for a cohort ? How/where to look up codes (e.g. from Epic front end or elsewhere).








