# Other sources R health help


### online communities

[NHSRCommunity](https://nhsrcommunity.com/) Friendly community promoting use of R in the NHS.

[NHSR on slack](http://nhsrcommunity.slack.com/)

[R for data science online learning community](https://www.rfordatasci.com/)
A welcoming community based around the book "R for Data Science".

[stackoverflow](https://stackoverflow.com/questions/tagged/r)
Where coders ask and answer questions. A good site just to search as a non-member but also worth joining. 
Good to use [Minimal Reproducible Examples (reprex)](https://stackoverflow.com/help/minimal-reproducible-example) both to help solve issues yourself and when asking on the site or of colleagues.


### training resources

[NHSR intro to R slides](https://nhs-r-community.github.io/intro_r/) & [repository](https://github.com/nhs-r-community/intro_r)
A complete intro to R & RStudio course that goes a little beyond what we cover in our intro. Includes data to run the practicals. We may go through some of these as revision and to explore further.

[RStudio Data Science in a Box](https://datasciencebox.org/)
A complete introduction to data science course.

[Datacamp](https://www.datacamp.com/courses/free-introduction-to-r)
Datacamp offer a wide range of interactive training for R and other data. There are some free introductory materials and more advanced available through a paid registration. You may be able to get funding support from the hospital. 


### books

[R for Health Data Science](https://argoshare.is.ed.ac.uk/healthyr_book/)
Free online version & hardcopies. Great 2021 book from a UK health perspective. Starts from beginner level, goes beyond what we covered e.g. into analysis & version control.

[R for Data Science](https://r4ds.had.co.nz/)
Free online version & hardcopies. Good for dplyr, ggplot & into analyses. A little dated maybe (2017).

[Data Visualization A practical Introduction](https://kjhealy.github.io/socviz/)
Hardcopy & associated R package with code to replicate the figures.


### R packages

These are all on CRAN so can be installed by `install.packages(NAME)`. Link below is to best description.

[NHSDataDictionaRy](https://cran.r-project.org/web/packages/NHSDataDictionaRy/vignettes/introduction.html)	
NHS Data Dictionary Tools

[Rdiagnosislist](https://cran.r-project.org/web/packages/Rdiagnosislist/vignettes/SNOMEDcodelists.html)

[NHSRdatasets](https://nhs-r-community.github.io/NHSRdatasets/)

[medicaldata](https://higgi13425.github.io/medicaldata/)
Medical datasets for teaching (US focus).










